service: budgety-backend

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  hello:
    handler: app/handler.hello
    events:
      - http:
          path: hello
          method: get
